version: "3"

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # ports:
    #   - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    restart: always
    networks:
      - common_net
      # - default

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - common_net
      # - default

  cryptonav_ui:
    container_name: cryptonav_ui
    image: cryptonav_ui:latest
    # build:
    #   context: .
    #   dockerfile: ./ui/Dockerfile
    #   # target: development
    #   target: build
    # ports:
    #   - "5173:5173"
    env_file:
      - .env
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    depends_on:
      - cryptonav_api
    restart: unless-stopped

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - common_net
      # - default

  cryptonav_api:
    container_name: cryptonav_api
    # image: cryptonav_api:lastest
    build:
      context: .
      dockerfile: ./fastapi/Dockerfile
      target: development
    # ports:
    #   - "8000:8000"
    env_file:
      - .env
    environment:
      ENVIRONMENT: "development" # or "production"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      LOG_LEVEL: "INFO"
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - common_net
      # - default

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

  nginx:
    # image: nginx:latest
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro # Gắn file cấu hình nginx
      - ./nginx/cache:/var/cache/nginx # Tùy chọn: gắn thư mục cache để giữ cache
      - ./nginx/ssl:/etc/nginx/ssl # Secure Sockets Layer (SSL) file: server-sample.crt, server-sample.key
      - ./nginx/html:/var/www/html # static html web for example
      - ./nginx/log:/var/log/nginx/
    # depends_on:
    #   - cryptonav_api
    #   - cryptonav_ui
    networks:
      # - default
      common_net:
        aliases:
          - ${DOMAIN_NAME}

networks:
  common_net:
    driver: bridge
