version: "3"

services:
  cryptonav-api:
    image: cryptonav-api:lastest
    container_name: cryptonav-api
    ports:
      - "8000:8000" # ánh xạ cổng API (nếu ứng dụng chạy trên cổng 8000)
    restart: unless-stopped

  cryptonav_ui:
    container_name: cryptonav_ui
    image: cryptonav_ui:latest
    ports:
      - "5173:5173"
    # volumes:
    # Mount the root folder that contains .git
    # - .:/workspace:cached
    # depends_on:
    #   - cryptonav_api
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d # configuration in default.conf
      - ./nginx/ssl:/etc/nginx/ssl # Secure Sockets Layer (SSL) file: server-sample.crt, server-sample.key
      - ./nginx/html:/var/www/html # static html web for example
      - ./nginx/log:/var/log/nginx/
      - ./certbot/letsencrypt:/etc/nginx/ssl/letsencrypt
    # depends_on:
    #   - cryptonav-api
    restart: unless-stopped
