version: "3"

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    restart: always

  cryptonav_ui:
    container_name: cryptonav_ui
    # image: cryptonav_ui:lastest
    build:
      context: .
      dockerfile: ./ui/Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    depends_on:
      - cryptonav_api
    restart: unless-stopped

    # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity
    command: /bin/sh -c "while sleep 1000; do :; done"

  cryptonav_api:
    container_name: cryptonav_api
    # image: cryptonav_api:lastest
    build:
      context: .
      dockerfile: ./fastapi/Dockerfile
      target: development
    ports:
      - "8000:8000"
    environment:
      ENVIRONMENT: "development" # or "production"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      JWT_SECRET_KEY: ${JWT_SECRET_KEY} # nên thay bằng khóa thực sự và bảo mật
      LOG_LEVEL: "INFO"
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    depends_on:
      - db
    restart: unless-stopped

    # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity
    command: /bin/sh -c "while sleep 1000; do :; done"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro # Gắn file cấu hình nginx
      - ./nginx/cache:/var/cache/nginx # Tùy chọn: gắn thư mục cache để giữ cache
      - ./nginx/ssl:/etc/nginx/ssl # Secure Sockets Layer (SSL) file: server-sample.crt, server-sample.key
      - ./nginx/html:/var/www/html # static html web for example
      - ./nginx/log:/var/log/nginx/
    # depends_on:
    # - cryptonav_api
