version: "3"

services:
  cryptonav-ui:
    container_name: cryptonav-ui
    # image: cryptonav-ui:lastest
    build:
      context: .
      dockerfile: ./ui/Dockerfile
      target: development
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    restart: unless-stopped

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  cryptonav-api:
    container_name: cryptonav-api
    # image: cryptonav-api:lastest
    build:
      context: .
      dockerfile: ./server/Dockerfile
      target: development
    ports:
      - "8000:8000"
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    restart: unless-stopped

    # Overrides default command so things don't shut down after the process ends.
    # command: /bin/sh -c "while sleep 1000; do :; done"
    command: sleep infinity
